# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cbe6994bde3aee586a25e4eb64e71dfa29040ccc81f8843a837beb9b8518d1c7bf50906e32941d7da9b9044e92fefa48c86ec16ac393b15d9c4e93ce13a6e8

test:
  secret_key_base: b7963b64899c23ffa464a9fafcb175be5945c4c4b47c82ef5d1c6648e8efeb2dcf87900442f567843bf8cf18014e33f44e68d91b1ab4f5a6d9e83f881d0008ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
